
dist: trusty


sudo: false


language: node_js


node_js:
    - '6'
    - '7'


install:
    - npm install -q


script:
    - npm test
    - npm run build


branches:
    except:
        - gh-pages


git:
    depth: 1


cache:
    directories:
        - node_modules

